In [2]:
#1
import numpy as np
a=np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [6]:
#2
a1=a.reshape(2, 6)
a2=a.reshape(3, 4)
a3=a.reshape(6, 2)
a4=a.reshape(4, 3)
a5=a.reshape(12, 1)
print(a1)
print(a2)
print(a3)
print(a4)
print(a5)

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


In [7]:
#3
a1=a.reshape(2, -1)
a2=a.reshape(3, -1)
a3=a.reshape(-1, 2)
a4=a.reshape(-1, 3)
a5=a.reshape(12, -1)
print(a1)
print(a2)
print(a3)
print(a4)
print(a5)

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


In [8]:
#4
x=np.arange(12, 24)
matr=x.reshape(3,4)
y=matr.reshape(12,1)
print(x)
print(y)

[12 13 14 15 16 17 18 19 20 21 22 23]
[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


In [9]:
#5
b=np.random.randn(3,4)
b

array([[-1.82113219, -0.08848339, -1.02612679, -0.54032842],
       [ 0.16439217,  0.2892754 , -0.82385898,  0.43933834],
       [ 0.59940909,  0.39671029,  1.7164653 ,  0.40583964]])

In [10]:
print(b.size)
b=b.flatten()
print(b.size)
b

12
12


array([-1.82113219, -0.08848339, -1.02612679, -0.54032842,  0.16439217,
        0.2892754 , -0.82385898,  0.43933834,  0.59940909,  0.39671029,
        1.7164653 ,  0.40583964])

In [11]:
#6
a=np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [12]:
#7
b=np.arange(20, 1, -2).reshape(1,10)
b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

In [13]:
#8
a = np.zeros((2, 2))
a

array([[0., 0.],
       [0., 0.]])

In [14]:
b = np.ones((3, 2))
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [15]:
v = np.vstack((a, b))
v

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [16]:
v.size

10

In [17]:
#9
a=np.arange(0, 12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [18]:
A=a.reshape(4,3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [19]:
At=A.T
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [20]:
B = np.dot(A, At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [21]:
B.shape

(4, 4)

In [22]:
B_inv=np.linalg.inv(B)
B_inv

LinAlgError: Singular matrix

In [23]:
#Вычислить обратную матрицу для матрицы B не получится, т.к. это вырожденная (сингулярная) матрица

In [24]:
#10
np.random.seed(42)

In [25]:
#11
c=np.random.randint(0, 16,16)
c

array([ 6,  3, 12, 14, 10,  7, 12,  4,  6,  9,  2,  6, 10, 10,  7,  4])

In [26]:
#12
C=c.reshape(4,4)
C

array([[ 6,  3, 12, 14],
       [10,  7, 12,  4],
       [ 6,  9,  2,  6],
       [10, 10,  7,  4]])

In [27]:
D=B+C*10
D

array([[ 65,  44, 143, 172],
       [114, 120, 206, 162],
       [ 83, 176, 169, 272],
       [132, 222, 282, 342]])

In [28]:
d=np.linalg.det(D)
d

-28511999.999999944

In [29]:
r=np.linalg.matrix_rank(D)
r

4

In [30]:
D_inv=np.linalg.inv(D)
D_inv

array([[ 0.00935396,  0.04486532,  0.05897517, -0.07286055],
       [-0.01503577, -0.00122896, -0.00192971,  0.00967873],
       [-0.00356692, -0.01782828, -0.04152146,  0.04326178],
       [ 0.00909091, -0.00181818,  0.01272727, -0.01090909]])

In [31]:
#13
D_inv=np.where(D_inv<0, 0,1)
D_inv

array([[1, 1, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [1, 0, 1, 0]])

In [32]:
print(B)
print(C)
E=np.where(D_inv==1, B, C)
E

[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]
[[ 6  3 12 14]
 [10  7 12  4]
 [ 6  9  2  6]
 [10 10  7  4]]


array([[  5,  14,  23,  14],
       [ 10,   7,  12, 122],
       [  6,   9,   2, 212],
       [ 32,  10, 212,   4]])